
 Volume in drive D is SHERING    
 Volume Serial Number is 1B1E-1301
 Directory of D:\HOSP\HOSL\INTRO

.              <DIR>        02-04-98  16:08
..             <DIR>        02-04-98  16:08
INTRO    SM2           331  02-04-98  16:09
INTRO    SM4           376  02-04-98  16:09
ATTRACT  SMK             0  02-04-98  16:09
         3 file(s)            707 bytes
         2 dir(s)     405,651,456 bytes free
